---
# Common variables
opt_laps_configure_gpo: false
opt_laps_install_client: false
opt_laps_install_powershell: false
opt_laps_install_server: false
opt_laps_install_ui: false
opt_laps_skip_reboot: false

# Server variables

# GPO variables
opt_laps_gpo_name: ansible-laps
opt_laps_password_policy_complexity: uppercase,lowercase,digits,symbols
opt_laps_password_policy_length: 14
opt_laps_password_policy_age: 30

opt_laps_domain_server: "ez-lab"
opt_laps_domain_username: "adnin"
opt_laps_domain_password: "passwed"
opt_laps_s3bucket: "installers-fja"
opt_laps_install: "C:\\installers"
opt_laps_file: "LAPS.x64.msi"
