---
#
# Ansible managed
#
repository:
  description: Install, configure, initialize and unseal Hashicorp Vault.
  homepage: https://robertdebock.nl/
  topics: vault, ansible, molecule, tox, playbook, hacktoberfest
