---
roles:
  - name: geerlingguy.certbot
  - name: geerlingguy.firewall
  - name: geerlingguy.ntp
  - name: geerlingguy.haproxy

collections:
  - amazon.aws
  - azure.azcollection
  - cisco.intersight
  - cisco.iosxr
  - cisco.ise
  - cisco.ucs
  - community.crypto
  - community.general
  - community.hashi_vault
  - community.mysql
  - community.vmware
  - community.windows
  - dellemc.powerflex
  - dellemc.enterprise_sonic
  - microsoft.ad
  - purestorage.flasharray
  - vmware.vmware_rest
  - middleware_automation.keycloak
