roles:
- geerlingguy.certbot

collections:
- amazon.aws
- ansible.windows
- azure.azcollection
- cisco.intersight
- cisco.iosxr
- cisco.ise
- cisco.ucs
- community.crypto
- community.general
- community.hashi_vault
- community.mysql
- community.vmware
- community.windows
- purestorage.flasharray
- vmware.vmware_rest