---
# tasks file for adfs
- name: Install requirements for CSV with sub features and management tools
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  with_items:
    - IPAM

- name: Reboot if installing feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required
