plugin: aws_ec2
# Take from environment
# aws_access_key: <YOUR-AWS-ACCESS-KEY-HERE>
# aws_secret_key: <YOUR-AWS-SECRET-KEY-HERE>
regions:
  - eu-west-1
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region