---
- name: Copy the guacamole_exporter systemd service file
  template:
    src: guacamole_exporter.service.j2
    dest: /etc/systemd/system/guacamole_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart guacamole_exporter

- name: Copy the guacamole_exporter config file
  template:
    src: guacamole_exporter.env.j2
    dest: "{{ guacamole_exporter_environment_file }}"
    owner: "{{ _guacamole_exporter_system_user }}"
    group: "{{ _guacamole_exporter_system_group }}"
    mode: 0600
  notify: restart guacamole_exporter

- name: Allow guacamole_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ guacamole_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
