---
- name: Create the guacamole_exporter group
  group:
    name: "{{ _guacamole_exporter_system_group }}"
    state: present
    system: true
  when: _guacamole_exporter_system_group != "root"

- name: Create the guacamole_exporter user
  user:
    name: "{{ _guacamole_exporter_system_user }}"
    groups: "{{ _guacamole_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: _guacamole_exporter_system_user != "root"

- block:
    - name: Download guacamole_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/tschoonj/guacamole_exporter/releases/download/v{{ guacamole_exporter_effective_version }}/guacamole_exporter-v{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/guacamole_exporter-{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}.tar.gz"
        checksum: "md5:{{ guacamole_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Create dest directory
      become: false
      file:
        path: "/tmp/guacamole_exporter-{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      check_mode: false

    - name: Unpack guacamole_exporter binary
      become: false
      unarchive:
        src: "/tmp/guacamole_exporter-{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/guacamole_exporter-{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}"
        creates: "/tmp/guacamole_exporter-{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}/guacamole_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate guacamole_exporter binaries
      copy:
        src: "/tmp/guacamole_exporter-{{ guacamole_exporter_effective_version }}-linux-{{ go_arch }}/guacamole_exporter"
        dest: "{{ _guacamole_exporter_binary_install_dir }}/guacamole_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart guacamole_exporter
      when: not ansible_check_mode
  when: guacamole_exporter_binary_local_dir | length == 0

- name: propagate locally distributed guacamole_exporter binary
  copy:
    src: "{{ guacamole_exporter_binary_local_dir }}/guacamole_exporter"
    dest: "{{ _guacamole_exporter_binary_install_dir }}/guacamole_exporter"
    mode: 0755
    owner: root
    group: root
  when: guacamole_exporter_binary_local_dir | length > 0
  notify: restart guacamole_exporter
