---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    guacamole_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in guacamole_exporter_web_listen_address"

- name: Check if guacamole_exporter is installed
  stat:
    path: "{{ _guacamole_exporter_binary_install_dir }}/guacamole_exporter"
  register: __guacamole_exporter_is_installed
  check_mode: false
  tags:
    - guacamole_exporter_install

- name: Gather currently installed guacamole_exporter version (if any)
  command: "{{ _guacamole_exporter_binary_install_dir }}/guacamole_exporter -version"
  args:
    warn: false
  changed_when: false
  register: __guacamole_exporter_current_version_output
  check_mode: false
  when: __guacamole_exporter_is_installed.stat.exists
  tags:
    - guacamole_exporter_install
    - skip_ansible_lint

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/tschoonj/guacamole_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set guacamole_exporter_effective_version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        guacamole_exporter_effective_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - guacamole_exporter_version == "latest"
    - guacamole_exporter_binary_local_dir | length == 0
  delegate_to: localhost
  run_once: true

- name: Set effective version if necessary
  set_fact:
    guacamole_exporter_effective_version: "{{ guacamole_exporter_version }}"
  when:
    - (guacamole_exporter_version != "latest") or
      (guacamole_exporter_binary_local_dir | length > 0)
  delegate_to: localhost
  run_once: true

- name: Get checksum list from github
  set_fact:
    guacamole_exporter_checksum: "{{ lookup('url', 'https://github.com/tschoonj/guacamole_exporter/releases/download/v' + guacamole_exporter_effective_version + '/guacamole_exporter-v' + guacamole_exporter_effective_version + '-linux-' + go_arch + '.tar.gz.md5') }}"
  run_once: true
  delegate_to: localhost
  when: guacamole_exporter_binary_local_dir | length == 0
