---
- hosts: tag_system_debian,!tag_type_guacamole
  become: true
  gather_facts: true
  strategy: free

  tasks:
    - name: install basic server
      ansible.builtin.include_role:
        name: debian_server
