---
# tasks file for domain_pdc
- name: Create new Windows domain in a new forest
  ansible.windows.win_domain:
    create_dns_delegation: no
    database_path: "{{ database_path }}"
    dns_domain_name: "{{ domain }}"
    domain_mode: "{{ domain_mode }}"
    domain_netbios_name: "{{ domain_netbios_name }}"
    forest_mode: "{{ forest_mode }}"
    safe_mode_password: "{{ safe_mode_password }}"
    sysvol_path: "{{ sysvol_path }}"
  register: domain_install

- name: enable ad recycle bin
  win_shell: |
    Import-Module ActiveDirectory
    # Get the distinguished name of the Active Directory domain
    $Domain = (Get-ADDomain).DistinguishedName
    Enable-ADOptionalFeature 'Recycle Bin Feature' -Scope ForestOrConfigurationSet -Target $Domain -Confirm:$false

- name: Reboot the machine with all defaults
  ansible.windows.win_reboot: