---
- name: Install requirements for CSV with sub features and management tools
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  with_items:
    - DirectAccess-VPN

- name: Reboot if installing feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required


- name: Configure DA
  win_shell: |
    Install-RemoteAccess `
    -DAInstallType FullInstall `
    -ConnectToAddress da.ez-lab.xyz `
    -ClientGPOName "ez-lab.xyz\DirectAccess Clients GPO" `
    -ServerGPOName "ez-lab.xyz\DirectAccess Server GPO" `
    -InternalInterface LAN `
    -InternetInterface INTERNET `
    -NLSURL https://nls.ez-lab.xyz `
    -Force
