---
# tasks file for debian_server

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: install gpg
  ansible.builtin.package:
    name:
      - aptitude
      - fusioninventory-agent
      - gnupg
    state: present

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
