---
# tasks file for simpana

- name: download bin to Ansible controller
  aws_s3:
    bucket: "{{ s3bucket }}"
    object: "{{ bin }}"
    dest: "/tmp/{{ bin }}"
    mode: get
  delegate_to: localhost

- name: copy s3 object from Ansible controller to Windows host
  win_copy:
    src: "/tmp/{{ bin }}"
    dest: "{{ dlroot }}\\{{ bin }}"

- name: download lic to Ansible controller
  aws_s3:
    bucket: "{{ s3bucket }}"
    object: "{{ xml }}"
    dest: "/tmp/{{ xml }}"
    mode: get
  delegate_to: localhost

- name: copy s3 object from Ansible controller to Windows host
  win_copy:
    src: "/tmp/{{ xml }}"
    dest: "{{ dlroot }}\\{{ bin }}"

- name: Reboot the machine with all defaults
  ansible.windows.win_reboot: