---
# tasks file for win-default

- name: Install standard tools
  win_chocolatey:
    name: {{ item }}
    state: present
  loop:
    - '7zip.install'
    - 'baretail'
    - 'curl'
    - 'git'
    - 'googlechrome'
    - 'laps'
    - 'notepadplusplus'
    - 'reportviewer2012'
    - 'sysinternals'
    - 'windirstat'