---
# tasks file for wac
- name: Install wac
  win_chocolatey:
    name: windows-admin-center
    state: present

# was

# mkdir $dldir
# Invoke-WebRequest -Uri https://aka.ms/WACDownload -OutFile $wacfile #DevSkim: ignore DS104456
# msiexec /i $wacfile /qn /L*v log.txt SME_PORT=$wacport SSL_CERTIFICATE_OPTION=generate

- name: Reboot the machine with all defaults
  ansible.windows.win_reboot:
