---
galaxy_info:
  role_name: win_chocolatey_server
  author: Jordan Borean
  description: Install Chocolatey Server on Windows role
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: Windows
    versions:
    - Server 2016
    - Server 2012 R2
    - Server 2012
    - Server 2008 R2
  galaxy_tags:
  - windows
  - packaging
  - chocolatey
dependencies: []
