---
- name: create self signed certificate for site if no cert thumbprint was specified
  block:

  - name: get or generate a self signed certificate for the https bindings
    win_gen_certificate:
    register: pri_chocolatey_server_https_certificate

  - name: set certificate thumbprint to out_chocolatey_server_https_certificate fact
    set_fact:
      out_chocolatey_server_https_certificate: '{{ pri_chocolatey_server_https_certificate.thumbprint }}'

  when: opt_chocolatey_server_https_certificate is not defined

- name: setup https binding
  win_iis_webbinding:
    name: chocolatey_server_site
    port: '{{ opt_chocolatey_server_https_port }}'
    state: present
    protocol: https
    certificate_hash: '{{ (opt_chocolatey_server_https_certificate is defined)|ternary(opt_chocolatey_server_https_certificate, out_chocolatey_server_https_certificate) }}'
  when: not ansible_check_mode  # site won't exist yet in check mode

- name: create firewall rule for HTTPS access
  win_firewall_rule:
    name: Chocolatey Server HTTPS (In)
    localport: '{{ opt_chocolatey_server_https_port }}'
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes
    profiles: '{{ opt_chocolatey_server_firewall_profiles }}'
    program: System
