---
- name: Install via chocolatey
  win_chocolatey:
    name: "{{ item }}"
    state: present
  ignore_errors: yes
  with_items:
    - 7zip.install
    - baretail
    - curl
    - git
    # - googlechrome
    - notepadplusplus
    - rdmfree
    - sysinternals
    - vscode
    - windirstat
