---
- name: Set the region format to {{ format }} and copy settings to new profiles
  ansible.windows.win_region:
    format: "{{ format }}"
    unicode_language: "{{ lang }}"
    location: "{{ location }}"
    copy_settings: true
  register: result

- name: reboot for local if needed
  ansible.windows.win_reboot:
  when: result.restart_required
