---
# - name: Change to swiss keyboard
#   win_shell: |
#     Set-WinSystemLocale fr-CH
#     $langList = New-WinUserLanguageList fr-CH
#     Set-WinUserLanguageList $langList -Force

- name: Make installers
  ansible.windows.win_file:
    path: C:\installers
    state: directory

# - name: Allow WinRM
#   win_shell: Configure-SMremoting.exe -enable

# - name: Enable Remoting
#   win_shell: |
#     winrm qc -Quiet
#     Enable-PSRemoting –Force

- name: disable ie esc
  include_tasks: ieesc.yml

- name: disable defender
  include_tasks: defender.yml

- name: manage smb
  include_tasks: smb.yml

- name: Include features
  include_tasks: features.yml

- name: Include chocolatey
  include_tasks: chocolatey.yml

- name: set powershell
  include_tasks: powershell.yml

- name: create admin
  include_tasks: admin.yml

- name: set locale
  include_tasks: locale.yml
# - name: Reboot the machine with all defaults
#   ansible.windows.win_reboot:
