---
# - name: Change to swiss keyboard
#   win_shell: |
#     Set-WinSystemLocale fr-CH
#     $langList = New-WinUserLanguageList fr-CH
#     Set-WinUserLanguageList $langList -Force

- name: Make installers
  ansible.windows.win_file:
    path: C:\installers
    state: directory

# - name: Allow WinRM
#   win_shell: Configure-SMremoting.exe -enable

# - name: Enable Remoting
#   win_shell: |
#     winrm qc -Quiet
#     Enable-PSRemoting –Force

- name: disable ie esc
  ansible.builtin.include_tasks: ieesc.yml
- name: disable defender
  ansible.builtin.include_tasks: defender.yml
- name: manage smb
  ansible.builtin.include_tasks: smb.yml
- name: Include features
  ansible.builtin.include_tasks: features.yml
- name: Include chocolatey
  ansible.builtin.include_tasks: chocolatey.yml
- name: set powershell
  ansible.builtin.include_tasks: powershell.yml
- name: create admin
  ansible.builtin.include_tasks: admin.yml
- name: set locale
  ansible.builtin.include_tasks: locale.yml
