---
- name: Ensure the required NuGet package provider version is installed
  ansible.windows.win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force
- name: install powershell modules
  community.windows.win_psmodule:
    name: "{{ item }}"
    skip_publisher_check: true
    state: present
  with_items:
    - PSPKI
    - PSExcel
    - Logging
    - AWSPowerShell
