---
- name: Disable LMHosts
  ansible.windows.win_shell: |
    $disable = 2
    $adapters = (gwmi win32_networkadapterconfiguration)
    foreach ($adapter in $adapters) {
      Write-Host $adapter
      $adapter.settcpipnetbios($disable)
    }
- name: Remove SMBv1
  ansible.windows.win_shell: Disable-WindowsOptionalFeature -Online -FeatureName smb1protocol -NoRestart
- name: Disable Netbios
  ansible.windows.win_shell: |
    $nicClass = Get-WmiObject -List Win32_NetworkAdapterConfiguration
    $nicClass.enableWins($false, $false)
- name: Disable EnableSMB1Protocol
  ansible.windows.win_shell: Set-SmbServerConfiguration -EnableSMB1Protocol $false -Confirm:$false
- name: Set-SmbServerConfiguration RequireSecuritySignature
  ansible.windows.win_shell: Set-SmbServerConfiguration -RequireSecuritySignature $true -EnableSecuritySignature $true -EncryptData $true -Confirm:$false
- name: Disable auto share
  ansible.windows.win_shell: Set-SmbServerConfiguration -AutoShareServer $false -AutoShareWorkstation $false  -Confirm:$false
- name: Disable hidden
  ansible.windows.win_shell: Set-SmbServerConfiguration -ServerHidden $true  -AnnounceServer $false  -Confirm:$false
