---
# tasks file for adfs
- name: Install requirements for CSV with sub features and management tools
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  with_items:
    - File-Services
    - FS-DFS-Namespace
    - FS-DFS-Replication
    - FS-Data-Deduplication
    - FS-Resource-Manager
    - FS-SyncShareService
    - RSAT-AD-PowerShell

- name: Reboot if installing feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required


# new-Partition -PartitionNumber 2  -DriveLetter D  | Format-Volume  -FileSystem NTFS   -Force:$true   -Compress   -UseLargeFRS  -Confirm:$false
- name: Disable smbv1
  ansible.windows.win_shell: |
    Set-SmbServerConfiguration `
      -EnableSMB1Protocol $false `
      -Confirm:$false

- name: Enable sign
  ansible.windows.win_shell: |
    Set-SmbServerConfiguration `
      -RequireSecuritySignature $true `
      -EnableSecuritySignature $true `
      -EncryptData $true `
      -Confirm:$false

- name: remove admin share
  ansible.windows.win_shell: |
    Set-SmbServerConfiguration -AutoShareServer $false `
      -AutoShareWorkstation $false `
      -Confirm:$false

- name: Run multi-lined shell commands
  ansible.windows.win_shell: |
    Set-SmbServerConfiguration -ServerHidden $true `
    -AnnounceServer $false `
    -Confirm:$false

- name: Restart a service
  ansible.windows.win_service:
    name: lanmanserver
    state: restarted

- name: Create directory structure
  ansible.windows.win_file:
    path: D:\samples
    state: directory

- name: Run multi-lined shell commands
  ansible.windows.win_shell: |
    Import-Module -Name DFSN
    Import-Module -Name ActiveDirectory

    $ad = Get-ADDomain
    $Domain = $ad.DNSRoot

    New-SmbShare `
      -Description "Sample file share" `
      -FolderEnumerationMode AccessBased `
      -CachingMode None `
      -Path D:\samples `
      -Name samples `
      -EncryptData $true `
      -Confirm:$false

    # Revoke-SmbShareAccess -Name samples `
    #   -AccountName 'Everyone' `
    #   -Confirm:$false | Out-Null

    # Grant-SmbShareAccess -Name samples -AccessRight Read `
    #   -AccountName 'ezlab\fjacquet' `
    #   -Confirm:$false | Out-Null

    # Grant-SmbShareAccess -Name samples -AccessRight Full `
    #   -AccountName 'NT Authority\SYSTEM' `
    #   -Confirm:$False | Out-Null

    # Grant-SmbShareAccess -Name samples -AccessRight Full `
    #   -AccountName 'CREATOR OWNER' `
    #   -Confirm:$false | Out-Null

    # New-DfsnRoot -Path \\$($domain)\samples `
    #   -TargetPath \\$($env:computername).$($Domain)\samples `
    #   -Type DomainV2 `
    #   -Description 'Samples Data DFS Root'

    # New-DfsReplicationGroup `
    #   -GroupName FSsamplesRG `
    #   -DomainName $($domain) `
    #   -Description 'Replication Group for FS-0,FS-1 shares' | Out-Null

    # Add-DfsrMember -GroupName FSsamplesRG `
    #   -Description 'File Server members' `
    #   -ComputerName $($env:computername).$($Domain),`
    #   -DomainName $($Domain) | Out-Null

    # New-DfsReplicatedFolder -GroupName FSsamplesRG `
    #   -FolderName Samples `
    #   -Domain $($Domain) `
    #   -Description 'Samples' `
    #   -DfsnPath \\$($Domain)\Samples | Out-Null
