---
# tasks file for adfs
- name: Install requirements for CSV with sub features and management tools
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  with_items:
    - IPAM
    - RSAT-AD-PowerShell

- name: Reboot if installing feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required

- name: Create GPO
  win_shell: |
    Invoke-IpamGpoProvisioning -Domain "{{ dns_domain }}" -GpoPrefixName "{{ gpo_prefix }}"   -Confirm:$false  -Force

# Import-Module -Name ActiveDirectory

# $Domain = $env:USERDNSDOMAIN



# $secret = (Get-SECSecretValue -SecretId "ez-lab.xyz/ad/fjacquet" -region eu-west-1).SecretString
# $username = "fjacquet@ez-lab.xyz"
# $password = ConvertTo-SecureString -AsPlainText -Force $secret
# $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username,$password

# Invoke-IpamGpoProvisioning `
#    –Domain $Domain `
#    -GpoPrefixName IPAM `
#    –IpamServerFqdn ipam-0.$domain `
#    -DelegatedGpoUser $Credential `
#    -Confirm:$false -Force
