---
- hosts: tag_type_glpi
  become: yes
  gather_facts: yes
  strategy: free

  tasks:
    - name: Install mysql
      include_role:
        name: linux_mysql

    - name: Install apache
      include_role:
        name: linux_apache
      vars:
        apache_state: started
        apache_vhosts:
          # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
          - servername: "glpi-0.ez-lab.xyz"
            documentroot: "/var/www/glpi"

    - name: Install php
      include_role:
        name: linux_php
      vars:
        php_memory_limit: "64M"
        php_file_uploads: "on"
        php_max_execution_time: "600"
        php_session_auto_start: "off"

    - name: Install glpi
      include_role:
        name: debian_glpi
