---
- hosts: tag_type_mgmt
  become: false
  gather_facts: false

  tasks:
    - name: install Chocolatey Server with the defaults
      ansible.builtin.include_role:
        name: win_chocolatey_server
