---
- hosts: tag_system_windows
  become: true
  gather_facts: true
  strategy: free

  tasks:
    - name: Join Domain
      ansible.builtin.include_role:
        name: win_domain_member

    - name: Install laps
      ansible.builtin.include_role:
        name: win_laps
