---
# tasks file for debian_redis

- name: install package
  package:
    name: redis-server
    state: present

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: restart redis

- name: start server
  service:
    name: redis-server
    enable: yes
    state: started
