---
- name: converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-vault
      vault_show_unseal_information: true
      vault_make_backup: true
      vault_kv_secrets:
        - name: my-secret
          data:
            foo: bar
            zip: zap
