---
# tasks file for rhel8_basic
- name: install some package
  yum:
    name:
      - wget
      - libaio
      - numactl
      - python
      - lsb
    state: present

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  register:

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"


# yum -y upgrade

# yum -y install wget libaio numactl python

# sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.old
# sudo sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
# sudo sed -i "s/#PermitRootLogin yes/PermitRootLogin yes/" /etc/ssh/sshd_config

# sudo systemctl restart sshd

# curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
# sudo python get-pip.py
# sudo pip install awscli

# INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)                                               #DevSkim: ignore DS137138
# REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}') #DevSkim: ignore DS137138
# HOSTNAME=$(aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" --region="$REGION" --output=text | awk '{print $5}')

# sudo hostnamectl set-hostname "$HOSTNAME".ez-lab.xyz
# sudo reboot
