---
# tasks file for guacamole

- name: Download guac-install.sh
  get_url:
    url: https://git.io/fxZq5
    dest: /usr/local/bin/guac-install.sh
    mode: '0775'

- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.command: /usr/local/bin/guac-install.sh --mysqlpwd "{{ mysql_password }}" --guacpwd "{{ guacamole_admin_password }}" --nomfa --installmysql